"""Type stubs for the fastconstmap C extension."""
from __future__ import annotations
from os import PathLike
from typing import Iterable, Mapping, Optional, Union

KeyT    = Union[str, bytes]
PathT   = Union[str, bytes, PathLike[str], PathLike[bytes]]
BufferT = Union[bytes, bytearray, memoryview]


class ConstMap:
    """Immutable map from strings to uint64.

    Returns an undefined value for keys not present in the original mapping.
    Memory: roughly 9 bytes per key.
    """

    def __init__(self, mapping: Mapping[KeyT, int]) -> None: ...
    def __getitem__(self, key: KeyT) -> int: ...
    def __len__(self) -> int: ...
    def get(self, key: KeyT) -> int: ...
    def get_many(self, keys: Iterable[KeyT]) -> list[int]: ...
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: BufferT) -> "ConstMap": ...
    def serialized_size(self) -> int: ...
    def write_into(self, buffer: BufferT) -> int: ...
    @classmethod
    def from_buffer(cls, buffer: BufferT) -> "ConstMap": ...
    def save(self, path: PathT) -> None: ...
    @classmethod
    def load(cls, path: PathT) -> "ConstMap": ...
    def nbytes(self) -> int: ...


class VerifiedConstMap:
    """Immutable map from strings to uint64 with missing-key detection.

    ``m[key]`` raises ``KeyError`` if the key was not in the original mapping.
    ``m.get(key, default=None)`` returns ``default`` instead. ``key in m``
    tests membership.

    Memory: roughly 18 bytes per key.
    """

    def __init__(self, mapping: Mapping[KeyT, int]) -> None: ...
    def __getitem__(self, key: KeyT) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __len__(self) -> int: ...
    def get(self, key: KeyT, default: Optional[int] = None) -> Optional[int]: ...
    def get_many(self, keys: Iterable[KeyT], default: Optional[int] = None) -> list[Optional[int]]: ...
    def to_bytes(self) -> bytes: ...
    @classmethod
    def from_bytes(cls, data: BufferT) -> "VerifiedConstMap": ...
    def serialized_size(self) -> int: ...
    def write_into(self, buffer: BufferT) -> int: ...
    @classmethod
    def from_buffer(cls, buffer: BufferT) -> "VerifiedConstMap": ...
    def save(self, path: PathT) -> None: ...
    @classmethod
    def load(cls, path: PathT) -> "VerifiedConstMap": ...
    def nbytes(self) -> int: ...
